name: SlimefunPrivateProtect
version: ${version}
main: org.nineteam.slimefunPrivateProtect.SlimefunPrivateProtect
api-version: '1.19'
depend: [ Slimefun ]
authors: [ Venom Lightning ]
description: Better protection on private territories
softdepend:
  - TranscEndence
  - CrystamaeHistoria
commands:
  check:
    permission: sfpp.check
  stats:
    permission: sfpp.stats
  reload:
    permission: sfpp.reload